#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url=jdbc:mysql://39.106.127.25:3306/vueblog?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=admin
#mybatis.config-location=classpath:/mybatis-config.xml
#
#
#server.port=8081
#logging.level.org.springframework.security=info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.106.127.25:3306/vueblog2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
#logging:
#  level: info
